"""requirements_memory.py — Persistent history of requirements verification results.

Maintains a rolling log of N runs so trends are visible over time.
Separate from the step-correction memory (memory_manager.py / memory.md).

Files:
  requirements_feedback.md  — append-only log of every --verify run
  requirements_memory.md    — consolidated trend analysis (rewritten on consolidate)
"""
from __future__ import annotations

import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from playwrightcli.requirements_verifier import RequirementsVerifier

_HERE = Path(__file__).parent

REQUIREMENTS_FEEDBACK_FILE = _HERE / "requirements_feedback.md"
REQUIREMENTS_MEMORY_FILE = _HERE / "requirements_memory.md"

# Also store structured data for programmatic trend analysis
REQUIREMENTS_HISTORY_FILE = _HERE / "requirements_history.jsonl"


class RequirementsMemory:
    """Tracks requirements verification results across runs."""

    def __init__(self) -> None:
        self._history: list[dict] = []
        self._load_history()

    # ------------------------------------------------------------------
    # History I/O
    # ------------------------------------------------------------------

    def _load_history(self) -> None:
        """Load all historical run records from JSONL file."""
        self._history = []
        if not REQUIREMENTS_HISTORY_FILE.exists():
            return
        for line in REQUIREMENTS_HISTORY_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    self._history.append(json.loads(line))
                except json.JSONDecodeError:
                    pass

    def _append_history(self, record: dict) -> None:
        """Append a single run record to the JSONL file."""
        REQUIREMENTS_HISTORY_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(REQUIREMENTS_HISTORY_FILE, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(record) + "\n")
        self._history.append(record)

    # ------------------------------------------------------------------
    # Record a verification run
    # ------------------------------------------------------------------

    def record_run(self, verifiers: list[RequirementsVerifier]) -> None:
        """Record results from a --verify run into feedback + history."""
        run_ts = datetime.now().isoformat(timespec="seconds")

        # Build structured record
        record = {
            "timestamp": run_ts,
            "portals": {},
        }

        for v in verifiers:
            portal_results = {}
            for r in v.results:
                portal_results[r.req_id] = {
                    "status": r.status,
                    "description": r.description,
                    "detail": r.detail,
                }
            record["portals"][v.portal] = {
                "pass": v.pass_count,
                "fail": v.fail_count,
                "skip": v.skip_count,
                "results": portal_results,
            }

        # Append to JSONL history
        self._append_history(record)

        # Append to human-readable feedback log
        self._append_feedback(run_ts, verifiers)

    def _append_feedback(self, run_ts: str, verifiers) -> None:
        """Append human-readable results to requirements_feedback.md."""
        lines = [f"\n## Verification Run {run_ts}"]

        for v in verifiers:
            total = v.pass_count + v.fail_count + v.skip_count
            lines.append(f"\n### {v.portal.upper()} — PASS: {v.pass_count}  FAIL: {v.fail_count}  SKIP: {v.skip_count}  ({total} checks)")

            for r in v.results:
                icon = {"PASS": "+", "FAIL": "!", "SKIP": "-"}[r.status]
                detail = f" — {r.detail}" if r.detail else ""
                lines.append(f"  [{icon}] {r.req_id}: {r.description}{detail}")

        REQUIREMENTS_FEEDBACK_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(REQUIREMENTS_FEEDBACK_FILE, "a", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")

    # ------------------------------------------------------------------
    # Consolidation — trend analysis
    # ------------------------------------------------------------------

    def consolidate(self) -> None:
        """Analyze all historical runs and rewrite requirements_memory.md with trends."""
        if not self._history:
            return

        lines = [
            "# certPortal Requirements Verification Memory",
            "",
            "<!-- Auto-generated by playwrightcli requirements memory. -->",
            f"<!-- Last consolidated: {datetime.now().isoformat(timespec='seconds')} -->",
            f"<!-- Total runs recorded: {len(self._history)} -->",
            "",
        ]

        # ---- Overall trend ----
        lines.append("## Run History Summary")
        lines.append("")
        lines.append("| Run | Timestamp | PASS | FAIL | SKIP |")
        lines.append("|-----|-----------|------|------|------|")

        for i, record in enumerate(self._history, 1):
            total_pass = sum(p["pass"] for p in record["portals"].values())
            total_fail = sum(p["fail"] for p in record["portals"].values())
            total_skip = sum(p["skip"] for p in record["portals"].values())
            lines.append(f"| {i} | {record['timestamp']} | {total_pass} | {total_fail} | {total_skip} |")
        lines.append("")

        # ---- Per-requirement trend ----
        # Collect all requirement IDs across all runs
        all_req_ids: set[str] = set()
        for record in self._history:
            for portal_data in record["portals"].values():
                all_req_ids.update(portal_data.get("results", {}).keys())

        # Build per-requirement timeline
        req_timelines: dict[str, list[dict]] = defaultdict(list)
        for record in self._history:
            for portal_data in record["portals"].values():
                for req_id, result in portal_data.get("results", {}).items():
                    req_timelines[req_id].append({
                        "timestamp": record["timestamp"],
                        "status": result["status"],
                    })

        # ---- Categorize requirements by health ----
        stable_pass: list[str] = []      # PASS on every run
        stable_fail: list[str] = []      # FAIL on every run
        regressions: list[tuple[str, str, str]] = []  # was PASS, now FAIL
        recoveries: list[tuple[str, str, str]] = []   # was FAIL, now PASS
        flapping: list[str] = []         # changed status 3+ times

        for req_id in sorted(all_req_ids):
            timeline = req_timelines[req_id]
            statuses = [t["status"] for t in timeline]

            if all(s == "PASS" for s in statuses):
                stable_pass.append(req_id)
            elif all(s == "FAIL" for s in statuses):
                stable_fail.append(req_id)
            else:
                # Count status changes
                changes = sum(1 for i in range(1, len(statuses)) if statuses[i] != statuses[i - 1])

                if changes >= 3:
                    flapping.append(req_id)
                elif len(statuses) >= 2:
                    prev = statuses[-2]
                    curr = statuses[-1]
                    if prev == "PASS" and curr == "FAIL":
                        regressions.append((req_id, timeline[-2]["timestamp"], timeline[-1]["timestamp"]))
                    elif prev == "FAIL" and curr == "PASS":
                        recoveries.append((req_id, timeline[-2]["timestamp"], timeline[-1]["timestamp"]))

        # ---- Write sections ----
        if regressions:
            lines.append("## Regressions (was PASS, now FAIL)")
            lines.append("")
            lines.append("| Requirement | Last PASS | First FAIL |")
            lines.append("|-------------|-----------|------------|")
            for req_id, last_pass, first_fail in regressions:
                lines.append(f"| {req_id} | {last_pass} | {first_fail} |")
            lines.append("")

        if recoveries:
            lines.append("## Recoveries (was FAIL, now PASS)")
            lines.append("")
            lines.append("| Requirement | Last FAIL | Recovered |")
            lines.append("|-------------|-----------|-----------|")
            for req_id, last_fail, recovered in recoveries:
                lines.append(f"| {req_id} | {last_fail} | {recovered} |")
            lines.append("")

        if flapping:
            lines.append("## Flapping (changed status 3+ times)")
            lines.append("")
            for req_id in flapping:
                timeline = req_timelines[req_id]
                history_str = " -> ".join(t["status"] for t in timeline[-5:])
                lines.append(f"- **{req_id}**: {history_str}")
            lines.append("")

        if stable_fail:
            lines.append("## Persistent Failures (FAIL on every run)")
            lines.append("")
            for req_id in stable_fail:
                desc = ""
                # Get description from latest run
                for record in reversed(self._history):
                    for portal_data in record["portals"].values():
                        if req_id in portal_data.get("results", {}):
                            desc = portal_data["results"][req_id].get("description", "")
                            break
                    if desc:
                        break
                lines.append(f"- **{req_id}**: {desc}")
            lines.append("")

        if stable_pass:
            lines.append(f"## Stable (PASS on all {len(self._history)} runs)")
            lines.append("")
            lines.append(f"{len(stable_pass)} requirements consistently passing:")
            lines.append("")
            # Group by prefix for readability
            prefix_groups: dict[str, list[str]] = defaultdict(list)
            for req_id in stable_pass:
                parts = req_id.rsplit("-", 1)
                prefix = parts[0] if len(parts) == 2 else req_id
                prefix_groups[prefix].append(req_id)

            for prefix, ids in sorted(prefix_groups.items()):
                lines.append(f"- **{prefix}**: {', '.join(ids)}")
            lines.append("")

        # ---- Per-requirement detailed timeline (last 10 runs) ----
        lines.append("## Detailed Timeline (last 10 runs)")
        lines.append("")

        recent_runs = self._history[-10:]
        run_headers = [r["timestamp"][-8:] for r in recent_runs]  # HH:MM:SS portion

        lines.append("| Requirement | " + " | ".join(run_headers) + " |")
        lines.append("|-------------|" + "|".join(["---"] * len(run_headers)) + "|")

        for req_id in sorted(all_req_ids):
            row = [req_id]
            for record in recent_runs:
                status = "—"
                for portal_data in record["portals"].values():
                    if req_id in portal_data.get("results", {}):
                        s = portal_data["results"][req_id]["status"]
                        status = {"PASS": "+", "FAIL": "!", "SKIP": "-"}.get(s, s)
                        break
                row.append(status)
            lines.append("| " + " | ".join(row) + " |")

        lines.append("")

        REQUIREMENTS_MEMORY_FILE.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Query helpers (for future use by route_discovery / dry-run)
    # ------------------------------------------------------------------

    def get_latest_status(self, req_id: str) -> str | None:
        """Return the most recent status for a requirement, or None if never tested."""
        for record in reversed(self._history):
            for portal_data in record["portals"].values():
                if req_id in portal_data.get("results", {}):
                    return portal_data["results"][req_id]["status"]
        return None

    def get_run_count(self) -> int:
        """Return total number of recorded verification runs."""
        return len(self._history)

    def get_consecutive_failures(self, req_id: str) -> int:
        """Return number of consecutive FAIL results for a requirement (from latest)."""
        count = 0
        for record in reversed(self._history):
            found = False
            for portal_data in record["portals"].values():
                if req_id in portal_data.get("results", {}):
                    if portal_data["results"][req_id]["status"] == "FAIL":
                        count += 1
                        found = True
                    else:
                        return count
            if not found:
                return count
        return count
