"""agents/dwight.py — Spec Analyst (PDF → THESIS.md).

INV-01: Dwight never imports from other agent files.
INV-04: No LangChain abstractions. Single deterministic GPT-4o call.

Pipeline:
  1. Download PDF from certportal-raw-edi bucket
  2. Extract text with pdfplumber
  3. Structure spec with GPT-4o (single call, deterministic prompt)
  4. Render THESIS.md from THESIS_TEMPLATE
  5. Write THESIS.md to S3 (versioned path if exists — never overwrites)
  6. Insert retailer_specs DB row
  7. Log to Monica

OpenAI usage: GPT-4o for PDF structuring (real call).

CLI: python -m agents.dwight --retailer <slug> --pdf-key <s3-key>
"""
from __future__ import annotations

import argparse
import asyncio
import json
from datetime import datetime, timezone
from typing import Any

import pdfplumber
from openai import OpenAI

from certportal.core import monica_logger
from certportal.core.config import settings
from certportal.core.workspace import S3AgentWorkspace, FileNotFoundInWorkspace

_openai_client = OpenAI(api_key=settings.openai_api_key)


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class ThesisAlreadyExists(Exception):
    """Raised if THESIS.md already exists at the target path. Caller must version."""


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------


THESIS_TEMPLATE = """# THESIS — {retailer_name} EDI Program
**Generated by:** Dwight
**Source PDF:** {source_pdf_key}
**Spec version:** {spec_version}
**Generated at:** {generated_at}
**Retailer slug:** {retailer_slug}

## Program Summary
{program_summary}

## Transaction Requirements
{transaction_requirements}

## Channel Configuration
{channel_configuration}

## Known Retailer-Specific Rules
{retailer_specific_rules}

## Dwight's Confidence Assessment
{confidence_assessment}
"""

DWIGHT_STRUCTURE_PROMPT = """You are an EDI specification analyst.
Extract structured data from this retailer Trading Partner Guide.
Return a JSON object with these exact keys:
- spec_version: string (e.g. "005010")
- program_summary: string (2-3 sentences)
- transaction_requirements: dict mapping transaction_code to {mandatory_segments, qualifiers, business_rules}
- channel_configuration: list of {channel, transactions, special_rules}
- retailer_specific_rules: list of {rule, segment, description}
- confidence_assessment: list of {section, confidence: "HIGH"|"MEDIUM"|"LOW", flag: string|null}
Return ONLY valid JSON. No markdown fences. No commentary."""


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def run(retailer_slug: str, pdf_s3_key: str) -> str:
    """Run Dwight's spec analysis pipeline.

    Args:
        retailer_slug: Retailer identifier (e.g. "elior")
        pdf_s3_key:    S3 key in certportal-raw-edi bucket

    Returns:
        S3 key of the written THESIS.md

    Raises:
        ThesisAlreadyExists: If THESIS.md already exists (caller must supply versioned path)
    """
    monica_logger.log(
        "DWIGHT",
        "A",
        f"Spec analysis started. retailer={retailer_slug} pdf={pdf_s3_key}",
        retailer_slug=retailer_slug,
    )

    workspace = S3AgentWorkspace(retailer_slug)  # Retailer-level scope

    # 1. Download PDF from raw-edi bucket
    monica_logger.log("DWIGHT", "A", f"Downloading PDF: {pdf_s3_key}", retailer_slug=retailer_slug)
    pdf_bytes = workspace.download_raw_edi(pdf_s3_key)

    # 2. Extract text with pdfplumber
    pdf_text = _extract_pdf_text(pdf_bytes)
    if not pdf_text.strip():
        monica_logger.log(
            "DWIGHT",
            "Q",
            f"WARNING: PDF text extraction returned empty content for {pdf_s3_key}. "
            f"Writing ambiguity flag.",
            retailer_slug=retailer_slug,
        )
        workspace.append_log(
            "GLOBAL-FEEDBACK.md",
            f"[{_utcnow_iso()}] [DWIGHT] AMBIGUITY: Empty PDF text for {pdf_s3_key}",
        )

    # 3. Structure spec with GPT-4o (single call, deterministic)
    monica_logger.log("DWIGHT", "A", "Calling GPT-4o for spec structuring.", retailer_slug=retailer_slug)
    structured = _structure_with_gpt4o(pdf_text, pdf_s3_key)

    # 4. Determine target S3 key for THESIS.md
    thesis_key = "THESIS.md"
    if workspace.exists(thesis_key):
        raise ThesisAlreadyExists(
            f"THESIS.md already exists for retailer '{retailer_slug}'. "
            f"Supply a versioned path to avoid overwrite."
        )

    # 5. Render THESIS.md
    retailer_name = retailer_slug.replace("-", " ").title()
    thesis_content = _render_thesis(
        retailer_name=retailer_name,
        retailer_slug=retailer_slug,
        source_pdf_key=pdf_s3_key,
        structured=structured,
    )

    # 6. Write THESIS.md to S3
    full_key = workspace.upload(thesis_key, thesis_content)
    monica_logger.log(
        "DWIGHT",
        "A",
        f"THESIS.md written to {full_key}",
        retailer_slug=retailer_slug,
    )

    # 7. Insert retailer_specs DB row (async call dispatched synchronously)
    try:
        asyncio.run(
            _insert_retailer_spec_db(
                retailer_slug=retailer_slug,
                spec_version=structured.get("spec_version", "unknown"),
                thesis_s3_key=full_key,
                source_pdf_key=pdf_s3_key,
            )
        )
    except Exception as exc:  # noqa: BLE001
        monica_logger.log(
            "DWIGHT",
            "Q",
            f"DB write failed (non-fatal): {exc!r}",
            retailer_slug=retailer_slug,
        )

    monica_logger.log(
        "DWIGHT",
        "A",
        f"Spec analysis complete for {retailer_slug}. THESIS at {full_key}.",
        retailer_slug=retailer_slug,
    )

    return full_key


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _extract_pdf_text(pdf_bytes: bytes) -> str:
    """Extract full text from PDF bytes using pdfplumber."""
    import io

    text_parts: list[str] = []
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text_parts.append(page_text)
    return "\n\n".join(text_parts)


def _structure_with_gpt4o(pdf_text: str, source_key: str) -> dict[str, Any]:
    """Single GPT-4o call to structure PDF content. No retry loops.

    If the response cannot be parsed as JSON, writes an ambiguity flag and
    returns a minimal default structure.
    """
    # Truncate to ~100k chars to stay within context limits
    truncated = pdf_text[:100_000]

    user_content = (
        f"Here is the Trading Partner Guide content:\n\n{truncated}\n\n"
        "Extract and return the JSON structure as specified."
    )

    response = _openai_client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": DWIGHT_STRUCTURE_PROMPT},
            {"role": "user", "content": user_content},
        ],
        max_tokens=4096,
        temperature=0.0,
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content.strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Ambiguity: GPT-4o did not return valid JSON
        monica_logger.log(
            "DWIGHT",
            "Q",
            f"GPT-4o returned non-JSON for {source_key}. Using minimal structure.",
        )
        return {
            "spec_version": "unknown",
            "program_summary": "Extraction failed — manual review required.",
            "transaction_requirements": {},
            "channel_configuration": [],
            "retailer_specific_rules": [],
            "confidence_assessment": [
                {
                    "section": "all",
                    "confidence": "LOW",
                    "flag": "JSON parse error — GPT-4o response was malformed",
                }
            ],
        }


def _render_thesis(
    retailer_name: str,
    retailer_slug: str,
    source_pdf_key: str,
    structured: dict[str, Any],
) -> str:
    """Render THESIS.md from template using structured data."""

    def _fmt(value: Any) -> str:
        if isinstance(value, (dict, list)):
            return json.dumps(value, indent=2)
        return str(value)

    confidence_items = structured.get("confidence_assessment", [])
    confidence_md = "\n".join(
        f"- **{item.get('section', '?')}** [{item.get('confidence', '?')}]"
        + (f": ⚠ {item['flag']}" if item.get("flag") else "")
        for item in confidence_items
    )

    return THESIS_TEMPLATE.format(
        retailer_name=retailer_name,
        retailer_slug=retailer_slug,
        source_pdf_key=source_pdf_key,
        spec_version=structured.get("spec_version", "unknown"),
        generated_at=_utcnow_iso(),
        program_summary=structured.get("program_summary", ""),
        transaction_requirements=_fmt(structured.get("transaction_requirements", {})),
        channel_configuration=_fmt(structured.get("channel_configuration", [])),
        retailer_specific_rules=_fmt(structured.get("retailer_specific_rules", [])),
        confidence_assessment=confidence_md or "_No confidence assessment available._",
    )


async def _insert_retailer_spec_db(
    retailer_slug: str,
    spec_version: str,
    thesis_s3_key: str,
    source_pdf_key: str,
) -> None:
    from certportal.core.database import get_pool

    pool = await get_pool()
    async with pool.acquire() as conn:
        await conn.execute(
            """
            INSERT INTO retailer_specs (retailer_slug, spec_version, thesis_s3_key, source_pdf_key)
            VALUES ($1, $2, $3, $4)
            """,
            retailer_slug,
            spec_version,
            thesis_s3_key,
            source_pdf_key,
        )


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Dwight — Spec Analyst (PDF → THESIS.md)")
    parser.add_argument("--retailer", required=True, help="Retailer slug (e.g. elior)")
    parser.add_argument("--pdf-key", required=True, help="S3 key in certportal-raw-edi bucket")
    args = parser.parse_args()

    result_key = run(retailer_slug=args.retailer, pdf_s3_key=args.pdf_key)
    print(f"THESIS.md written to: {result_key}")
